[project]
name = "nextop-firewall"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydivert>=2.1.0",
    "scapy>=2.6.1",
]
